### ISSUE TITLE
Provide error information

### ISSUE THREAD

**Issue by mapu77** [pleo-io/assign-random-codeowners#62]
Hi folks, thanks for creating this tool. I truly believe you're filling a gap in CODEOWNERS feature, it has helped to address some issues in the past. I'd like to bring some issue regarding it's usage.

### Context
For a repository structure with different modules, in which each module is owned by a team, when I run the `assign-random-codeowners` the assignment fails unexpectedly and does not provide more information of why (specifically when requesting for team members) See screenshot attached.

I've tried to fetch the members using a personal token and Github API for GH Enterprise Server 3.7 and it worked as expected, so team exists in organization.

### Steps to reproduce

I provide here some kind of generalization to the problem itself

`CODEOWNERS`
``` CODEOWNERS
*                  @someteam
/sub-module-1/**   @another-team
/sub-module-2/**   @yet-another-team
```

`Github Action`
``` yml
on:
  pull_request:
    types:
      - ready_for_review # only interested in triggering when PR is ready for review
  workflow_dispatch: # allow manual trigger

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # default job GH token has enough permissions

jobs:
  assign-reviewers:
    runs-on: small
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Assign reviewers
        uses: pleo-io/assign-random-codeowners@v0.2.7
        with:
          reviewers-to-assign: 1 # takes into account already assigned reviewers
          assign-from-changed-files: true # narrows down reviewers to files CODEOWNERS
          assign-individuals-from-teams: true # assigns members from a team, instead of the entire team

```
![Screenshot 2023-04-17 at 13 09 07](https://user-images.githubusercontent.com/11423097/232489675-1fa9bf46-07d9-44f4-815e-863c31322dfc.png)
