### ISSUE TITLE
Seems to not reference github team correctly

### ISSUE THREAD

**Issue by khgould** [pleo-io/assign-random-codeowners#66]
codeowners file includes
* @org/team_name

reviewer_assignement:
```
name: Assign Random CODEOWNERS Reviewers
on:
  pull_request:
    types: [ opened, reopened ]
    branches: [ dev, prod ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign-random-codeowners:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Assign Random CODEOWNERS Reviewers
        uses: pleo-io/assign-random-codeowners@v0.2.7
        with:
          reviewers-to-assign: 1
          assign-individuals-from-teams: true
```

error:
```
Run pleo-io/assign-random-codeowners@v0.2.7
Found CODEOWNERS at .github/CODEOWNERS
Parsed CODEOWNERS:
[{"pattern":"*","owners":["@org/team_name"]}]
Requesting current reviewers in PR #146 via the GitHub API.
[200] Found assigned reviewer teams:
["DST"]
[200] Found assigned reviewer users:
[]
Requesting team members for team 'org/@org/team_name' via the GitHub API.
Error: HttpError: Not Found
```
